# Use the official Golang image as the base image
FROM 1.24-bookworm

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod tidy

# Copy the rest of the application code
COPY . .

# Build the Go application
RUN go build -o dummyservice .

# Expose the port the application runs on
EXPOSE 8080

# Command to run the executable
CMD ["./dummyservice"]