FROM alpine:latest AS builder

RUN apk add --no-cache busybox

# Create a minimal root filesystem
RUN mkdir -p /rootfs/bin /rootfs/lib /rootfs/binaries && \
    cp /bin/busybox /rootfs/busybox && \
    cp /lib/ld-musl-*.so.1 /rootfs/lib/ && \
    # install busybox symlinks inside /rootfs/bin
    chroot /rootfs /busybox --install -s /bin

ARG TARGETOS
ARG TARGETARCH

COPY bin/** /binaries/
WORKDIR /binaries

RUN find . -type f ! -name "*.$TARGETOS-$TARGETARCH" -delete && \
    for f in *."$TARGETOS-$TARGETARCH"; do \
      [ -e "$f" ] && mv "$f" "${f%.$TARGETOS-$TARGETARCH}"; \
    done

FROM scratch

# Copy minimal filesystem
COPY --from=builder /rootfs/ /

# Copy the already-renamed binaries
COPY --from=builder /binaries/ /

# Default command
CMD ["/bin/ls", "-lrt", "/"]