version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_service.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/test/... {{.ROOT_DIR}}/internal/...'
      COMPONENTS: 'api-server db-migrator event-reconciler task-cli task-scheduler task-worker tenant-manager tenant-manager-cli'
      CHART_COMPONENTS: 'dummy-service dummy-service-second'
      SKIP_VALIDATION_TESTS: 'true'
      OVERWRITE_COMPONENTS: 'true'

      BUILD_IMAGE_MODE: 'single-multi'
      SINGLE_IMAGE_NAME: 'cmk-full-base'
      SINGLE_DOCKER_FILE_IDENTIFIER: 'cmk-full-base'

      IMG_COMPONENTS: 'cmk-full-base cmk-full-plugins api-server api-server-plugins event-reconciler db-migrator task-cli task-scheduler task-scheduler-plugins task-worker tenant-manager tenant-manager-cli'


      #      SKIP_VALIDATION_TESTS: 'true'

      #      IMG_COMPONENTS: 'dummy-service dummy-service-2'
      #      CHART_COMPONENTS: 'dummy-service dummy-service-second'
      #      OVERWRITE_COMPONENTS: true

      #      COMPOSITE_COMPONENT_NAME: dummy-service-2
      #      COMPOSITE_DOCKER_FILE_IDENTIFIER: "dummy-service"
      #      COMPOSITE_BASE_IMAGE_NAME: "dummy-service:dummy-service"
      #      COMPOSITE_PLUGINS_IMAGE_NAME: "dummy-plugins:dummy-plugins"

      #
      COMPOSITE_COMPONENTS:
        - COMPONENT_NAME: cmk-full-plugins
          DOCKER_FILE_IDENTIFIER: cmk-full-plugins
          BASE_IMAGE_NAME: dummy-service:cmk-full-base
          PLUGINS_IMAGE_NAME: dummy-plugins:dummy-plugins
        - COMPONENT_NAME: api-server-plugins
          DOCKER_FILE_IDENTIFIER: cmk-api-server-plugins
          BASE_IMAGE_NAME: dummy-service:api-server
          PLUGINS_IMAGE_NAME: dummy-plugins:dummy-plugins
        - COMPONENT_NAME: task-scheduler-plugins
          DOCKER_FILE_IDENTIFIER: cmk-task-scheduler-plugins
          BASE_IMAGE_NAME: dummy-service:task-scheduler
          PLUGINS_IMAGE_NAME: dummy-plugins:dummy-plugins