version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_service.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/test/... {{.ROOT_DIR}}/internal/...'
      COMPONENTS: 'dummy-service dummy-service-second'
      DESTINATION_COMPONENT_NAME: dummy-service-2
      CORE_IMAGE_NAME: "dummy-service"
      PLUGIN_IMAGE_NAMES: "dummy-plugins"
      DOCKER_FILE_COMPOSITE_IDENTIFIER: "dummy-service"
      IMG_COMPONENTS: 'dummy-service dummy-service-2'
      CHART_COMPONENTS: 'dummy-service dummy-service-second'
