version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_plugins_test.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/test/... {{.ROOT_DIR}}/internal/...'
      COMPONENTS: 'dummy-service dummy-service-second'
      REPO_URL: 'https://github.com/openkcm/dummy-service'
