---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checker.name" . }}-config
  namespace: {{ include "checker.namespace" . }}
  labels:
    {{- include "checker.labels" . | nindent 4 }}
immutable: {{ .Values.config.isImmutable | default false }}
data:
  config.yaml: |-
    application:
      name: {{ .Chart.Name }}


