---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "checker.serviceAccountName" . }}-cluster-role
  namespace: {{ include "checker.namespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
      - configmaps
      - secrets
      - nodes
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "checker.serviceAccountName" . }}-cluster-role-binding
  namespace: {{ include "checker.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "checker.serviceAccountName" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "checker.serviceAccountName" . }}
    namespace: {{ include "checker.namespace" . }}

