name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - 'charts/**'
      - 'docs/**'
      - 'LICENSES/**'
      - '.releases/**'
      - '.github/**'
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: openkcm/build/.github/workflows/ci.svc.yaml@main
    secrets: inherit

