name: Use OpenKCM Pipeline Template

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  use-template:
    uses: openkcm/pipeline-template/.github/workflows/pipeline.yaml@feature/libary
    with:
      go-version: '1.24'
      gcp-service-account-key: "test"
      gcp-project-id: "test"
      app-name: 'dummy-service'
