name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/app.cmk.push.composite-image.yaml@3f96d77c0c9ef8db529f8d2999d3ef753b35cc1b
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
