name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@7257453ac4555878391b4a4d0757441776481891
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
