name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/cmk-release.image.yaml@5e17c8703081a86e49dee3a73dacb99240474ed2
    secrets: inherit
