name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@4e11df7e7d22cb9d149ba0c28f7a281ca2a9b007
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
