name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@c76f4645fbbc08ca663ca13cd74a520d5e73a49c
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
