name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@167e8abacd69c553def1364eff0ac18fe23be068
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
