name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/app.cmk.push.composite-image.yaml@edc76cd871969008baf237e4f6eccde45e33bb40
    secrets: inherit
