name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/cmk-release.image.yaml@44e7fb878c3526d9edc145ad93162adebb412bf5
    secrets: inherit
