name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@a0f4166719ba49eed9542f7aafa4dbe1e1c315fd
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
