name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@7136110b41ad81bd63577be3629e8f0f065713ca
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
