name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-composite-publish.yaml@81fa86e07f71556bca81e69be50abc1875abbd4a
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
