name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/app.cmk.push.composite-image.yaml@537289ee7a225dca3a24479a1e24a453ccf610a9
    secrets: inherit
