name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/app.cmk.push.composite-image.yaml@dc25fcc4e20a47ed9a0c803f6e13d31fc6f3582c
    secrets: inherit
