name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: read

jobs:
  release:
    uses: openkcm/build/.github/workflows/app.cmk.push.composite-image.yaml@2a8a3d7a0e675d319bbaa6f042150800e946b0d9
    secrets: inherit
