name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/apps-cmk-publish.yaml@3a0bc197d417782a579ebb92f0a43996aff32caf
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
