name: Release CMK

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes

permissions:
  packages: write
  contents: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/app.cmk.push.composite-image.yaml@37f121e06727e3222df9837f72292c8ed89c47f3
    with:
      image_signing_enabled: true
      ocm_signing_enabled: true
    secrets: inherit
