name: REUSE Compliance Check

on:
  push:
    paths-ignore:
      - 'charts/**'
      - 'docs/**'
      - 'LICENSES/**'
      - '.releases/**'
      - '.github/**'
  pull_request:

permissions:
  contents: read

jobs:
  run:
    uses: openkcm/build/.github/workflows/reuse.yaml@main
    secrets: inherit
