name: SBOM Testing

on:
  push:
    branches:
      - main
      - testing/sbom
  release:
    types: [published]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  release_tag:
    name: Release version
    runs-on: ubuntu-24.04
    steps:
      - name: Generate token from GitHub App
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_PUSH_TAG_ID }}
          private_key: ${{ secrets.APP_PUSH_TAG_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive

      - name: Generate Build Version
        uses: hashicorp/actions-generate-metadata@f6f1ca9cededa05d841a58d171064faf3de8ec74 #main
        id: execute
        with:
          repositoryOwner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          version: cat VERSION
          product: dummy-service
          metadataFileName: ${{ github.workspace }}/build_version.json

      - name: Print Build Version
        shell: bash
        run: cat ${{ github.workspace }}/build_version.json

      - name: Checkout Taskfile repo
        run: |
          git clone -b testing/sbom https://github.com/openkcm/build.git ./hack/common

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 #v2.0.0
        with:
          version: 3.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Generate SBOM
        run: |
          task cyclonedxgomod:app --verbose


      - name: Clean up SBOM files
        run: |
          echo "Removing the following SBOM files:"
          rm -f *.sbom.json
          rm -rf bin/

