name: TestPipeline

on:
  push:
    branches:
      - feature/*
      - bug/*
      
permissions: write-all

jobs:
  use-template:
    uses: openkcm/pipeline-template/.github/workflows/test.yaml@main
    with:
      go-version: '1.24'
      app-name: 'dummy-service'
