name: Upload Release Assets

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-24.04

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output  # adjust to your actual artifact name

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            *sbom.json
            *vuln.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
